version: '3'
services:
  xds:
    build: server
  envoy:
    build: .
    ports:
      - "10000:10000"
      - "9901:9901"
  nginx1:
    image: nginx:latest
  nginx2:
    image: nginx:latest
  httpd1:
    image: httpd:latest
  httpd2:
    image: httpd:latest
